config/routes.rb
Rails.application.routes.draw do

  get 'redeems/index'
  post 'redeems' => "redeems#code_enter"
  get '/deals/redeem_code/:deal_code' => "redeems#redeem_code"
  post '/deals/validate-timings' => "deals#validate_timings"

  delete "/delete_admins/:id" => "admins#destroy"
  resources :specials
  resources :users
  resources :roles

  get "/redeems" => "redeems#index"

  devise_scope :admin do
    authenticated :admin do
      root 'home#dashboard', as: :authenticated_root
    end
    unauthenticated :admin do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "/generate_stamp/:id" => "deals#generate_stamp"

  get "/special_branch_ids/:id" => "specials#get_branch_ids"

  get "/get_prefill_text/:id" => "businesses#get_prefill_text"

  get "/search_keywords" => "businesses#search_keywords"
  post "/add_keyword" => "businesses#add_keyword"
  post "/assign_business" => "admins#assign_business"
  get "/businesses/search_name" => "businesses#search_name"
  get "/admin_businesses/:admin_id" => "admins#get_businesses"

  post "/frequent_search/:type" => "deals#frequent_search"

  get '/get_ruby_date/:date' => "deals#get_ruby_date"

  get '/deals/week_view(/:date(/:window))' => "deals#week_view"

  get '/cloudinary_upload' => "images#cloudinary_upload"

  get '/charts_by_week' => "home#charts_by_week"

  get '/invite_users', to: "admins#invite_users"
  get '/branches/search/', to: "branches#search_by_business_name"
  get '/branches/branches_deals/', to: "branches#branches_deals"
  get '/reinvite/:id', to: "admins#reinvite", as: :reinvite
  resources :admins, only: :new
  post '/send_invitation', to: "admins#send_invitation"

  resources :categories
  resources :businesses do
    collection { post :search, to: 'businesses#index' }
    collection { get :search, to: 'businesses#index' }
    collection { get :autocomplete, to: 'businesses#autocomplete' }
    resources :branches do
      collection { post :search, to: 'branches#index' }
      collection { get :search, to: 'branches#index' }
    end

  end
  resources :countries
  resources :areas
  resources :cities

  resources :deals do
    collection { post :search, to: 'deals#index' }
    collection { get :search, to: 'deals#index' }
  end

  devise_for :admins

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  # load_and_authorize_resource

  before_action :set_business, only: [:show, :update, :edit, :approve, :disapprove, :destroy]

  def search_name
    businesses = Business.where("name like '#{params[:q]}%'").select("id,concat(id,'-',name) as name")
    respond_to do |format|
      format.json { render :json => businesses.map(&:attributes) }
    end
  end

  def get_prefill_text
    @business = Business.find(params[:id].to_i)
    render json: @business
  end

  def search_keywords
    @keywords = Keyword.where("name like ?", "#{params[:q]}%")
    respond_to do |format|
      format.json { render :json => @keywords.map(&:attributes) }
    end
  end

  def add_keyword
    resp = write("post","api/keywords",{keyword: {name: params[:keyword]}})
  end

  def index
    authorize! :list, Business
    @q = fetch_businesses.order("created_at DESC").ransack(params[:q])
    @businesses = @q.result.includes(:category).page(params[:page]).per(params[:limit] || 20)
    @branches_count = Branch.joins(:business).where("businesses.id IN (#{(@businesses.map &:id).join(",")})").group(:business_id).count if !@businesses.blank?
  end

  def fetch_businesses
    if current_admin.admin?
      Business
    else
      current_admin.businesses
    end
  end

  def new
    print 'test'
    authorize! :create, Business
    @business = Business.new
    1.times{ @business.images.build}
  end

  def create
    create_or_update("post","new")
  end

  def update
    create_or_update("put","edit")
  end

  def edit
    authorize! :update, Business
    @images = @business.images
  end

  def create_or_update(method,url)
    path = "api/businesses"
    path = path + "/#{@business.id}" if method == "put"
    business = business_params
    business = format_image(business) if business["images_attributes"].present?
    business = format_keywords(business) if business[:add_keywords].present?
    resp = write(method,path,{'business' => business })
    if resp["response"]["business"].present?
      # business_id = business["response"]["business"]["id"]
      redirect_to businesses_path #(business_id)
    else
      res = resp["response"]
      out = res.map{|k,v| "#{k} - #{v.join(",")}"}.join(',')
      flash[:error] = out
      redirect_to send("#{url}_business_path")
    end
  end

  def show

  end

  def destroy
    authorize! :delete, Business
    business = write("delete","api/businesses/#{@business.id}")
    if business["response"]["message"] == "Deleted Successfully!"
      redirect_to businesses_path
    else
      redirect_to businesses_path
    end
  end

  def autocomplete
    result = Array.new
    res = Business.autocomplete(params[:q])
    render json: res.map { |r|  {"id" => r.id,"label" => "#{r.name}"}} if res.present?
    #render json: res.map(&:name)
  end

  private

  def format_keywords(p)
    keywords = p[:add_keywords]
    arr = []
    keywords.split(",").each do |i|
      arr << {"keyword_id" => i}
    end
    p[:keywords] = arr
    p.delete(:add_keywords)
    p
  end

  def set_business
    @business = Business.find(params[:id])
  end

  def business_params
    params.require(:business).permit!#(:id,:_destroy,:name, :category_id, :description, :website, :facebook, :keywords, :twitter, :logo, :state, images_attributes: [:original, :medium, :thumb])
  end

end

app/helpers/businesses_helper.rb
module BusinessesHelper

end

app/views/businesses/_add_keyword.html.erb
<div style="display: none;" class="modal fade" id="modal-top" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-top">
    <div class="modal-content">
      <div class="block block-themed block-transparent remove-margin-b">
        <div class="block-header bg-primary-dark">
          <ul class="block-options">
            <li>
              <button data-dismiss="modal" type="button"><i class="si si-close"></i></button>
            </li>
          </ul>
          <h3 class="block-title">Add New Keyword</h3>
        </div>
        <div class="block-content">
          <div class="row">
            <%= form_tag "/add_keyword",{remote: true} do %>

              <div class="form-group col-md-12">
                <div class="col-md-8 name">
                  <input class="form-control" type="text" value="" name="keyword" >
                </div>
                <div class="col-md-4 name">
                  <input type="submit" name="commit" value="Save" class="btn-lg btn-sm btn-success">
                </div>
              </div>

            <% end %>

          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-sm btn-default" type="button" data-dismiss="modal">Close</button>
        <button class="btn btn-sm btn-primary" type="button" data-dismiss="modal"><i class="fa fa-check"></i> Ok</button>
      </div>
    </div>
  </div>
</div>

app/views/businesses/_form.html.erb
<% categories = Category.where('parent_id IS NULL') %>
<%= nested_form_for @business, :html => {:class => 'form-horizontal js-validation-bootstrap' } do |f| %>
  <% if flash[:error] %>
    <div class="col-sm-12">
      <div class="block">
        <div class="block-header">
          <code>
            Errors:
            <%= flash[:error] %>
          </code>
        </div>
      </div>
    </div>
  <% end %>
  <div class="col-md-6">
    <div class="block block-themed">
      <div class="block-header bg-primary">
        <h3 class="block-title">Basic</h3>
      </div>

      <div class="block-content">

        <%= form_element("name",f,:text_field,[class: "form-control"],10,true,true) %>

        <%= form_element("category_id",f,:collection_select,[categories,:id,:name,{},{class: "form-control"}],10,true,true) %>

        <%= form_element("description",f,:text_area,[size: "200x5", class: "form-control"]) %>

        <%= form_element("add_keywords",f,:text_field,[class: "form-control", data: {pre: f.object.keywords.map(&:attributes).to_json}]) %>

        <div class="form-group col-md-10 text-center">
          <%= link_to "Add keyword","#",{data: {target: "#modal-top",toggle: "modal"}} %>
        </div>
        <div class="form-group"></div>


      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="block block-themed">
      <div class="block-header bg-primary">
        <h3 class="block-title">Social</h3>
      </div>
      <div class="block-content">

        <% hsh = {"website" => "wifi"} %>
        <% %w(website).each do |i| %>

          <% icon = hsh[i].nil? ? i : hsh[i] %>
          <div class="form-group">
            <div class="col-md-10">
              <div class="input-group d-flex">
                <span class="w50 input-group-addon"><i class="fa fa-<%= icon %>"></i></span>
                <%= f.text_field i.to_sym, {class: "form-control", placeholder: "#{i.titleize}"} %>
              </div>
            </div>
          </div>
        <% end %>

        <%= form_element("logo",f,:text_field,[class: "form-control"],10,true,true) %>
        <%= form_element("logo_preview",f,:text_field,[class: "form-control"],8,false) %>

        <div class="form-group"> </div>
        <div class="form-group"> </div>
        <div class="form-group"> </div>

      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="block block-themed">
      <div class="block-header bg-primary">
        <h3 class="block-title">Images</h3>
      </div>
      <div class="block-content business_images">
        <%= render 'images', f: f %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="block block-themed">
      <div class="block-header bg-primary">
        <h3 class="block-title">Prefill Text</h3>
      </div>
      <div class="block-content">
        <%= form_element("terms_and_conditions",f,:text_area,[size: "200x5", class: "form-control"]) %>
        <% if false %>
        <%= form_element("redeem_steps",f,:text_area,[size: "200x5", class: "form-control"]) %>
        <% end %>
        <div class="form-group"> </div>
      </div>
    </div>
  </div>

  <div class="row form-group text-center">
    <div class="col-xs-12">
      <div class="form-material">
        <p><%= f.submit "Save Business", :class => "btn-lg btn-sm btn-success"%></p>
      </div>
    </div>
  </div>

<% end %>

<%= render "add_keyword" %>

<script type="text/javascript">
actmm("businesses")
</script>

app/views/businesses/_images.html.erb
<div class="row form-group">
  <div class="col-xs-12">
    <div class="form-material">
      <p>

      <%= f.fields_for :images do |image| %>
        <div class="col-md-6 mycontent-left">
          <div class="text-right">
            <%= image.link_to_remove "<i class='fa fa-trash'></i>".html_safe %>
          </div>
          <%= form_element(["original","image_url"],image,:text_field,[class: "form-control business_image"]) %>
          <%= form_element("image_preview",f,:text_field,[class: "form-control"],8,false) %>
          <%= image.hidden_field :medium,{class: "medium"} %>
          <%= image.hidden_field :thumb,{class: "thumb"}  %>
        </div>
      <% end %>
      <%= f.link_to_add "Add Image", :images, :class => "btn btn-sm btn-info mt-25 ml-20 add_image_link"%>

      </p>
    </div>
  </div>
</div>

app/views/businesses/_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="text-center"><%= sort_link @q, :id %></th>
        <th class="text-center"><%= sort_link @q, :name %></th>
        <th class="text-center"><%= sort_link @q, :category_name, "Category" %></th>
        <th class="text-center">Branches</th>
        <th class="text-left">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @businesses.each do |business| %>
      <% branches_count = @branches_count[business.id].to_i %>
      <tr>
        <td class="text-center"> <%= business.id %> </td>
        <td class="text-center"> <%= link_to business.name, edit_business_path(business) %> </td>
        <td class="text-center"> <%= business.category.try(:name) %> </td>
        <td class="text-center"> <%= link_to branches_count, business_branches_path(business) %>  </td>
        <td class="text-left">
          <% if (branches_count == 0) && (can? :delete, Business) %>
            <%= link_to (raw('<i class="fa fa-trash-o fa-2"></i>')), business, method: :delete, class: 'btn-sm btn-danger', data: { confirm: 'Are you sure?'} %>
          <% else %>
            <i class="btn-sm btn-default fa fa-trash-o fa-2"></i>
          <% end %>
            <%#= business.approved? ? link_to((raw('Disapprove <i class="glyphicon glyphicon-remove"></i>')), business_disapprove_path(business), method: :post, class: 'btn btn-xs btn-default') : link_to((raw('Approve <i class="glyphicon glyphicon-ok"></i>')), business_approve_path(business), method: :post, class: 'btn btn-xs btn-default') %>
            <% if can? :create, Branch %>
            <%= link_to (raw('Add Branch')), new_business_branch_path(business), {:class => 'btn-sm btn-success'} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/businesses/add_keyword.js.erb
$("#modal-top").modal("hide");

app/views/businesses/edit.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        Edit Business
      </h1>
    </div>
    <div class="text-right">
      <%= link_to (raw('<i class="fa fa-arrow-left"></i> Back')), businesses_path, {:class => 'btn btn-xs btn-default'} %>
    </div>
  </div>
</div>
<%= render 'form', text: 'Edit Business' %>
<script>
  $(function(){
    $("#business_logo, .business_image").trigger("focusout");
  });
</script>

app/views/businesses/index.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        Businesses <small>(<%= @businesses.total_count %>)</small>
      </h1>
    </div>
    <% if can? :create, Business %>
    <div class="col-sm-5 text-right">
      <%= link_to (raw('<i class="fa fa-plus"></i> New Business')), new_business_path, {:class => 'btn btn-success'} %>
    </div>
  <% end %>
  </div>
</div>

<div class="block">
  <div class="block-content">
    <% if @businesses.present? %>

      <%= search_form_for @q, url: search_businesses_path, method: :post do |f| %>
        <div class="row col-sm-12">

          <div class="col-sm-2 pagination">
            <%= f.text_field :id_eq,{placeholder: "Id..", class: "form-control"} %>
          </div>
          <div class="col-sm-2 pagination">
            <%= f.text_field :name_cont,{placeholder: "Name..", class: "form-control"} %>
          </div>
          <div class="col-sm-1 pagination">
            <%= f.submit "Search", {class: "btn btn-info"} %>
          </div>
          <div class="col-sm-7">
            <%= paginate @businesses %>
          </div>

        </div>
      <% end %>
      <%= render 'table' %>
    <% else %>
      <h3 class="text-center" style="padding-bottom:20px;">Currently no businesses to show.</h3>
    <% end %>
  </div>
</div>
<script>
  actmm("businesses");
</script>

app/views/businesses/new.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        New Business
      </h1>
    </div>
    <div class="text-right">
      <%= link_to (raw('<i class="fa fa-arrow-left"></i> Back')), businesses_path, {:class => 'btn btn-xs btn-default'} %>
    </div>
  </div>
</div>
<%= render 'form', text: 'New Business'%>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>
<div class="content bg-gray-lighter">
  <div class="row items-push">
      <div class="col-sm-7">
          <h1 class="page-heading">
              Show
          </h1>
      </div>
      <div class="col-sm-5 text-right">
        <%= link_to (raw('<i class="fa fa-arrow-left"></i> Back')), businesses_path, {:class => 'btn btn-xs btn-default'} %>
      </div>
  </div>
</div>
<div class="block">
    <div class="block-content">
        <div class="table-responsive">
            <table class="table table-striped table-borderless table-header-bg">
                <thead>
                    <tr>
                      <th class="text-center">Name</th>
                        <th class="text-center">Category</th>
                        <th class="text-center">Description</th>
                        <th class="text-center">Website</th>
                        <th class="text-center">Twitter</th>
                        <th class="text-center">Logo</th>
                        <th class="text-center">Keywords</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td class="text-center"><%= @business.name %></td>
                      <td class="text-center"><%= @business.category.try(:name) %></td>
                      <td class="text-center"><%= @business.description %></td>
                      <td class="text-center"><%= @business.website %></td>
                      <td class="text-center"><%= @business.twitter %></td>
                      <td class="text-center"><%= @business.logo %></td>
                      <td class="text-center">
                          <div class="btn-group">
                              <%= link_to (raw('<i class="fa fa-pencil"></i>')), edit_business_path(@business), {:class => 'btn btn-xs btn-default'} %>
                          </div>
                      </td>
                    </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>