config/routes.rb
Rails.application.routes.draw do

  get 'redeems/index'
  post 'redeems' => "redeems#code_enter"
  get '/deals/redeem_code/:deal_code' => "redeems#redeem_code"
  post '/deals/validate-timings' => "deals#validate_timings"

  delete "/delete_admins/:id" => "admins#destroy"
  resources :specials
  resources :users
  resources :roles

  get "/redeems" => "redeems#index"

  devise_scope :admin do
    authenticated :admin do
      root 'home#dashboard', as: :authenticated_root
    end
    unauthenticated :admin do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "/generate_stamp/:id" => "deals#generate_stamp"

  get "/special_branch_ids/:id" => "specials#get_branch_ids"

  get "/get_prefill_text/:id" => "businesses#get_prefill_text"

  get "/search_keywords" => "businesses#search_keywords"
  post "/add_keyword" => "businesses#add_keyword"
  post "/assign_business" => "admins#assign_business"
  get "/businesses/search_name" => "businesses#search_name"
  get "/admin_businesses/:admin_id" => "admins#get_businesses"

  post "/frequent_search/:type" => "deals#frequent_search"

  get '/get_ruby_date/:date' => "deals#get_ruby_date"

  get '/deals/week_view(/:date(/:window))' => "deals#week_view"

  get '/cloudinary_upload' => "images#cloudinary_upload"

  get '/charts_by_week' => "home#charts_by_week"

  get '/invite_users', to: "admins#invite_users"
  get '/branches/search/', to: "branches#search_by_business_name"
  get '/branches/branches_deals/', to: "branches#branches_deals"
  get '/reinvite/:id', to: "admins#reinvite", as: :reinvite
  resources :admins, only: :new
  post '/send_invitation', to: "admins#send_invitation"

  resources :categories
  resources :businesses do
    collection { post :search, to: 'businesses#index' }
    collection { get :search, to: 'businesses#index' }
    collection { get :autocomplete, to: 'businesses#autocomplete' }
    resources :branches do
      collection { post :search, to: 'branches#index' }
      collection { get :search, to: 'branches#index' }
    end

  end
  resources :countries
  resources :areas
  resources :cities

  resources :deals do
    collection { post :search, to: 'deals#index' }
    collection { get :search, to: 'deals#index' }
  end

  devise_for :admins

end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController

  before_action :set_business, only: [:new, :create, :edit, :update, :index]
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  def index
    @q = @business.branches.order("created_at DESC").ransack(params[:q])
    @branches = @q.result.includes(:area).page(params[:page]).per(params[:limit] || 20)
    respond_to do |format|
      format.html
      format.json {render json: result}
    end
  end

  def new
    authorize! :create, Branch
    @branch = @business.branches.new
  end

  def show
    authorize! :read, Branch
  end

  def create
    create_or_update("post","new")
  end

  def update
    create_or_update("put","edit")
  end

  def create_or_update(method,url)
    path = "api/branches"
    path = path + "/#{@branch.id}" if method == "put"
    branch = branch_params
    branch[:business_id] = params[:business_id]
    branch = format_image(branch) if branch["images_attributes"].present?
    branch = format_attachments(branch) if branch["attachments_attributes"].present?
    branch = process_params(branch)
    puts branch
    resp = write(method,path,{'branch' => branch })
    puts resp
    if resp["response"]["branch"].present?
      # branch_id = branch["response"]["branch"]["id"]
      redirect_to business_branches_path #(branch_id)
    else
      res = resp["response"]
      out = res.map{|k,v| ("#{k} - #{v.join(",")}" rescue nil)}.join(',')
      flash[:error] = out

      render :new
    end
  end

  def process_params(b)
    b = process_timeslots(b)
    b = process_weekdays(b)
  end

  def process_timeslots(b)
    b[:time_slots] = Hash.new()
    %w(sun mon tue wed thu fri sat).each do |i|
      b[:time_slots][i] = Array.new()
      start_time = b[:timing][i][0]
      end_time = b[:timing][i][1]
      start_time = time_to_seconds(start_time) if start_time.present?
      end_time = time_to_seconds(end_time) if end_time.present?
      b[:time_slots][i][0] = start_time.to_s + "-" + end_time.to_s
      if b[:timing][i].length == 4
        start_time_2 = time_to_seconds(b[:timing][i][2])
        end_time_2 = time_to_seconds(b[:timing][i][3])
        b[:time_slots][i][1] = start_time_2.to_s + "-" + end_time_2.to_s
      end
    end
    b.delete(:timing)
    b
  end

  def process_weekdays(b)
    b[:working_days] = Array.new()
    weekday_mapping = {
      sun: "Sunday", mon: "Monday", tue: "Tuesday", wed: "Wednesday", thu: "Thursday", fri: "Friday", sat: "Saturday"
    }
    weekday_mapping.each do |key, day|
      if b[key] == "1"
        b[:working_days] << day
      end
      b.delete(key)
    end
    b
  end

  def edit
    authorize! :update, Branch
  end

  def destroy
    authorize! :delete, Branch
    resp = write("delete","api/branches/#{@branch.id}",{})
    redirect_to businesses_path
  end

  def branches_deals
    hsh = {}
    Business.find_by(name: params[:q]).branches.map {|i| hsh[i.id] = [i.id,i.name,0,i.area.try(:name)] }
    branches_deals = Deal.find(params[:deal_id]).branches_deals

    if !((branches_deals.map &:branch_id) & hsh.keys).blank?
      branches_deals.map {|i| hsh[i.branch_id][2] = (hsh[i.branch_id].present? ? i.original_qty : "false") }
    end
    render json: hsh.values
  end

  def search_by_business_name
    business = Business.find_by(name: params[:q])
    branches = business.branches
    area_ids = branches.pluck(:area_id)
    areas = Area.where(id: area_ids).select(:id,:name).as_json
    hsh = {}
    areas.map {|i| hsh[i["id"]] = i["name"]}
    branch_data = branches.pluck(:id, :name, :area_id)
    branch_data = branch_data.map{|arr| [arr[0],arr[1],hsh[arr[2]]] }
    result = {
      business_terms: business.terms_and_conditions,
      branches: branch_data
    }
    render json: result
  end

  private

  def branch_params
    params.require(:branch).permit!#(:name, :working_days, :open_time, :close_time, :address, :branch_area, :landline, :additional_info, :location_id, :business_id, :state, :latitude, :longitude, :sun, :mon, :tue, :wed, :thu, :fri, :sat)
  end

  def set_business
    @business = Business.find_by(id: params[:business_id])
  end

  def set_branch
    @branch = Branch.find_by(id: params[:id])
  end

end

app/views/branches/_attachments.html.erb
<div class="row form-group">
  <div class="col-xs-12">
  <h6 class="branch-top-notice">
    Please upload attachments specific to this branch. Please note the file name of the attachment will be visible on your branch listing.
  </h6>
  <div class="form-material">
    <div class="text-center cloudinary-upload-status"></div>
    <%= f.fields_for :attachments do |attachment| %>
      <div class="attachment-set">
        <div class="pull-right">
          <%= attachment.link_to_remove "<i class='fa fa-trash'></i> Delete attachment".html_safe, class: 'btn btn-xs btn-danger' %>
        </div>
        <div class="block-content">
          <%= form_element("title",attachment,:text_field,[class: "form-control"],6,true,false,false,true) %>
          <div class="row">
            <%= attachment.fields_for :images do |image| %>
              <div class="col-md-4 mt-5 mycontent-left">
                <div class="text-right">
                  <%= image.link_to_remove "<i class='fa fa-trash'></i>".html_safe %>
                </div>
                <%= form_element(["image","image_url"],image,:text_field,[class: "form-control branch_attachment_image cloudinary-url-field"]) %>
                <%= form_element("image_preview",f,:text_field,[class: "form-control"],8,false) %>
                <%= form_tag('upload_images', :method => :post, :class =>'new_upload', :enctype => 'multipart/form-data') do %>
                  <div class="row">
                    <div class="col-sm-6 text-warning text-center">
                      <%= cl_image_upload_tag(:image_id, :crop => :limit,
                                              :html => {accept: "image/*", :class => "image_upload form-control", :name => "upload_images"}) %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
            <%= attachment.link_to_add "Add Image", :images, :class => "btn btn-sm btn-info mt-25 ml-30 add_image_link"%>
          </div>
        </div>
      </div>
    <% end %>
    <%= f.link_to_add "Add Attachment", :attachments, :class => "btn btn-sm btn-info mt-25 ml-30 add_image_link"%>
  </div>
  </div>
</div>

app/views/branches/_form.html.erb
<% areas = Area.all %>
<% if flash[:error] %>
  <div class="col-sm-12">
    <div class="block">
      <div class="block-header">
        <code>
          Errors:
          <%= flash[:error] %>
        </code>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <div class="js-wizard-simple block">
      <ul class="nav nav-tabs nav-justified grey-bg">
        <li class="active">
          <a href="#tab-branch" data-toggle="tab">Branch Information</a>
        </li>
        <li class="">
          <a href="#tab-gallery" data-toggle="tab">Gallery</a>
        </li>
        <li class="">
          <a href="#tab-attachments" data-toggle="tab">Attachments</a>
        </li>
      </ul>
    </div>

    <div class="block-content tab-content">
      <div class="tab-pane fade fade-up push-50 active in" id="tab-branch">
        <div class="col-lg-6">
          <div class="block-content">
            <%= form_element(['name', 'Branch Name'],f,:text_field,[class: "form-control"],12,true,true,false) %>
            <%= form_element(['description', 'Branch Description'],f,:text_area,[size: "200x4", class: "form-control"],12,true,false,false) %>
            <%= form_element("area_id",f,:collection_select,[areas,:id,:name,{},{class: "form-control"}],12,true,true,false) %>
            <%= form_element("address",f,:text_field,[class: "form-control"],12,true,true,false,false) %>
            <%= form_element("longitude",f,:text_field,[class: "form-control"],12,true,false,6) %>
            <%= form_element("latitude",f,:text_field,[class: "form-control"],12,true,false,6) %>
            <%= form_element("mobile",f,:text_field,[class: "form-control"],12,true,false,6) %>
            <%= form_element("landline",f,:text_field,[class: "form-control"],12,true,false,6) %>
            <%= form_element("logo",f,:text_field,[class: "form-control branch-logo"],10,true,true) %>
            <%= form_element("logo_preview",f,:text_field,[class: "form-control"],8,false) %>
            <%= form_tag('upload_images', :method => :post, :class =>'new_upload', :enctype => 'multipart/form-data') do %>
              <div class="col-sm-6 text-warning text-center">
                <%= cl_image_upload_tag(:image_id, :crop => :limit,
                                        :html => {accept: "image/*", :class => "image_upload form-control", :name => "upload_images"}) %>
              </div>
            <% end %>
            <div class="form-group"></div>

          </div>
        </div>
        <div class="col-lg-6">
          <div class="block-content">
            <div class="row">
              <div class="col-md-12">
                <div class="time-slot-head time-slot-left-col">Auto Fill Timings</div>
                <span class="common-time-first">
                  <input type="text" class="form-control branch-time time-slot-change" value="9:00am" data-loc='1'>
                  to
                  <input type="text" class="form-control branch-time time-slot-change" value="12:00pm" data-loc='2'>
                </span>
                <span id="common-time-second-head" style="display: none;">
                  <input type="text" class="form-control branch-time time-slot-change" value="1:00pm" disabled="disabled" data-loc='3'>
                  to
                  <input type="text" class="form-control branch-time time-slot-change" value="9:00pm" disabled="disabled" data-loc='4'>
                </span>
                <a class="btn btn-success btn-sm" id="add-timing-head" data-root='true'>
                  <i class="fa fa-plus"></i> Add Timing
                </a>
                <a class="btn btn-danger btn-sm" id="remove-timing-head" data-root='true' style="display: none;">
                  <i class="fa fa-times"></i>
                </a>
              </div>
            </div>
            <div class="push-20-t row">
              <div class="col-md-12 time-slot-head">
                Work Days
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                Open
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                Close
              </div>
            </div>
            <div>
              <% %w(sun mon tue wed thu fri sat).each do |i| %>
                <div class="row push-20-t time-slot-item">
                  <div class="col-md-12">
                    <div class="time-slot-left-col">
                      <label class="css-input switch switch-sm switch-success">
                        <%= f.check_box i.to_sym, {}, 1, 0 %><span></span><%= i.upcase %>
                      </label>
                    </div>
                    <span class="common-time-first">
                      <input type="text" name="branch[timing][<%= i %>][]" class="form-control branch-time time-slot-loc-1" value="9:00am" data-day="<%= i %>">
                      to
                      <input type="text" name="branch[timing][<%= i %>][]" class="form-control branch-time time-slot-loc-2" value="12:00pm" data-day="<%= i %>">
                    </span>
                    <span class="common-time-second" style="display: none;">
                      <input type="text" name="branch[timing][<%= i %>][]" class="form-control branch-time time-slot-loc-3" value="1:00pm" disabled="disabled" data-day="<%= i %>">
                      to
                      <input type="text" name="branch[timing][<%= i %>][]" class="form-control branch-time time-slot-loc-4" value="9:00pm" disabled="disabled" data-day="<%= i %>">
                    </span>
                    <a class="btn btn-success btn-sm add-timing-common"><i class="fa fa-plus"></i> Add Timing</a>
                    <a class="btn btn-danger btn-sm remove-timing-common" style="display: none;"><i class="fa fa-times"></i></a>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="tab-pane fade fade-up push-30-t push-50" id="tab-gallery">
        <div class="block-content branch_images">
          <%= render 'images', f: f %>
        </div>
      </div>
      <div class="tab-pane fade fade-up push-30-t push-50" id="tab-attachments">
        <div class="block-content branch_images">
          <%= render 'attachments', f: f %>
        </div>
      </div>
    </div>

    <div class="row form-group text-center">
      <div class="col-xs-12">
        <div class="form-material">
          <p><%= f.submit "Save Branch", :class => "btn-lg btn-sm btn-success" %></p>
        </div>
      </div>
    </div>

  </div>
</div>

  
<script>
  actmm("businesses");
  image_cloudinary_upload_generic('.block-content', '.branch-logo');
  $(document).ready(function() {
    $('.time-slot-change').change(function() {
      var loc = $(this).data('loc');
      var time = $(this).val();
      $('.time-slot-loc-' + loc).val(time)
    });

    $('#new_branch').submit(function(e) {
      var branchName = $('#branch_name').val();
      var branchArea = $('#branch_area_id').val();
      if (branchName == '' || branchArea == '') {
        notys("Fill mandatory fields of the form to proceed!","error");
        return false;
      }

      var mobile = $('#branch_mobile').val();
      var landline = $('#branch_landline').val();
      if (mobile == '' && landline == '') {
        notys("Please enter either a mobile or landline number!","error");
        return false;
      }

      var weekSel = $('input[type="checkbox"]:checked').length;
      if (weekSel == 0) {
        notys("Please select active work days!","error");
        return false;
      }

      return true;
    });
  });
</script>

app/views/branches/_images.html.erb
<div class="row form-group">
  <div class="col-xs-12">
    <h6 class="branch-top-notice">
      Upload images specific to this branch (500x500 resolution). Please remove any business info images not relevant to this branch.
    </h6>
    <div class="form-material">
      <div class="text-center cloudinary-upload-status"></div>
      <p>

      <%= f.fields_for :images do |image| %>
        <div class="col-md-6 mycontent-left">
          <div class="text-right">
            <%= image.link_to_remove "<i class='fa fa-trash'></i>".html_safe %>
          </div>
          <%= form_element(["original","image_url"],image,:text_field,[class: "form-control branch_image cloudinary-url-field"]) %>
          <%= form_element("image_preview",f,:text_field,[class: "form-control"],8,false) %>
          <%= image.hidden_field :medium,{class: "medium"} %>
          <%= image.hidden_field :thumb,{class: "thumb"}  %>
          <%= form_tag('upload_images', :method => :post, :class =>'new_upload', :enctype => 'multipart/form-data') do %>
            <div class="row">
              <div class="col-sm-6 text-warning text-center">
                <%= cl_image_upload_tag(:image_id, :crop => :limit,
                                        :html => {accept: "image/*", :class => "image_upload form-control", :name => "upload_images"}) %>
            </div>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= f.link_to_add "Add Image", :images, :class => "btn btn-sm btn-info mt-25 ml-20 add_image_link"%>

      </p>
    </div>
  </div>
</div>

app/views/branches/_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="text-center"><%= sort_link @q, :id %> &nbsp;<i class="fa fa-sort"></i></th>
      <th class="text-center"><%= sort_link @q, :name %> &nbsp;<i class="fa fa-sort"></i></th>
      <th class="text-center"><%= sort_link @q, :area_name, "Area" %> &nbsp;<i class="fa fa-sort"></i></th>
      <th class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @branches.each do |b| %>
      <tr>
        <td class="text-center"> <%= @business.id %> - <%= b.id %> </td>
        <td class="text-center"> <%= link_to b.name, edit_business_branch_path(@business.id, b.id) %> </td>
        <td class="text-center"> <%= b.area.try(:name) %> </td>
        <td class="text-center">
          <% if can? :delete, Branch %>
            <%= link_to (raw('<i class="fa fa-trash-o fa-2"></i>')),business_branch_path(b.business, b), method: :delete, class: 'btn-sm btn-danger', data: { confirm: 'Are you sure?'} %>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/branches/edit.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        Edit Branch
      </h1>
    </div>
  </div>
</div>
<%= nested_form_for(@branch, url: business_branch_path(@business, @branch), method: :put, :html => {:class => 'form-horizontal js-validation-bootstrap'}) do |f| %>
  <%= render 'form', f: f, text: 'Edit' %>
<% end %>
<script>
  $(function(){
    $(".branch-logo").trigger("focusout");
    $(".branch_image").trigger("focusout");
    $(".branch_attachment_image").trigger("focusout");

    var time_slots = {}
    <% %w(sun mon tue wed thu fri sat).each do |i| %>
      time_slots['<%= i %>'] = []
    <% end %>
    <% @branch.branch_time_slots.each do |b| %>
      time_slots['<%= b[:day] %>'].push('<%= seconds_to_time(b[:start_time].to_i) %>');
      time_slots['<%= b[:day] %>'].push('<%= seconds_to_time(b[:end_time].to_i) %>');
    <% end %>
    $.each(time_slots, function(day, slots) {
      if (slots.length > 2) {
        $('input[data-day="' + day + '"]').parents('.time-slot-item').find('.add-timing-common').click();
      }
      var count = 0
      $('input[data-day="' + day + '"]').each(function() {
        if (slots.length > count) {
          $(this).val(slots[count])
        }
        count+=1;
      });
    });
    if ($('.add-timing-common:visible').length == 0) {
      $('#add-timing-head').click();
    }
    var branchLogo = $('#branch_logo').val();
    if (branchLogo.length == '') {
      $('#branch_logo').val('<%= @business.logo %>').trigger("focusout");
    }
  });
</script>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        <%= @business.id %>. <%= @business.name %><small> - (<%= @branches.count %> branches)</small>
      </h1>
    </div>
    <% if can? :create, Branch %>
    <div class="col-sm-5 text-right">
      <%= link_to (raw('<i class="fa fa-chevron-left"></i> Back')), businesses_path, {:class => 'btn btn-default'} %>
    </div>
    <% end %>
  </div>
</div>
<div class="block">
  <div class="block-content">
    <div class="table-responsive">
      <%= search_form_for @q, url: search_business_branches_path, method: :post do |f| %>
        <div class="row col-sm-12">

          <div class="col-sm-2 pagination">
            <%= f.text_field :id_eq,{placeholder: "Branch ID", class: "form-control"} %>
          </div>
          <div class="col-sm-2 pagination">
            <%= f.text_field :name_cont,{placeholder: "Branch Name", class: "form-control"} %>
          </div>
          <div class="col-sm-1 pagination">
            <%= f.submit "Search", {class: "btn btn-info"} %>
          </div>
          <div class="col-sm-7">
            <%= paginate @branches %>
          </div>
          <%= link_to (raw('<i class="fa fa-plus"></i> New Branch')), new_business_branch_path(@business), {:class => 'btn btn-success pull-right'} %>

        </div>
      <% end %>

      <%= render "table" %>
    </div>
  </div>
</div>
<script>
  actmm("businesses")
</script>

app/views/branches/index.js.erb
$('#specific_branches').html("<%= escape_javascript(render :partial => 'deals/specific_branches') %>");

app/views/branches/new.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        Add Branch
      </h1>
    </div>
  </div>
</div>

<%= nested_form_for(@branch, url: business_branches_path(@business), method: :post, :html => {:class => 'form-horizontal push-10-t push-10' }) do |f| %>
  <%= render 'form', f: f,text: 'Add' %>
<% end %>

<script>
  $("#open_days input").prop('checked', true);
  $('#branch_logo').val('<%= @business.logo %>').trigger("focusout");
</script>

app/views/branches/show.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
      <div class="col-sm-7">
          <h1 class="page-heading">
              Show
          </h1>
      </div>
      <div class="col-sm-5 text-right">
        <%= link_to (raw('<i class="fa fa-arrow-left"></i> Back')), business_branches_path(@branch.business), {:class => 'btn btn-xs btn-default'} %>
      </div>
  </div>
</div>
<div class="block">
    <div class="block-content">
        <div class="table-responsive">
            <table class="table table-striped table-borderless table-header-bg">
                <thead>
                    <tr>
                      <th class="text-center">Name</th>
                        <th class="text-center">Open Time</th>
                        <th class="text-center">Close Time</th>
                        <th class="text-center">Address</th>
                        <th class="text-center">Landline</th>
                        <th class="text-center">Mobile</th>
                        <th class="text-center">Additional Info</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                      <td class="text-center"><%= @branch.name %></td>
                      <td class="text-center"><%= @branch.open_time %></td>
                      <td class="text-center"><%= @branch.close_time %></td>
                      <td class="text-center"><%= @branch.address %></td>
                      <td class="text-center"><%= @branch.landline %></td>
                      <td class="text-center"><%= @branch.mobile %></td>
                      <td class="text-center"><%= @branch.additional_info %></td>
                      <td class="text-center">
                          <div class="btn-group">
                              <%= link_to (raw('<i class="fa fa-pencil"></i>')), edit_business_branch_path(@branch.business, @branch), {:class => 'btn btn-xs btn-default'} %>
                          </div>
                      </td>
                    </tr>
                </tbody>
              </table>
        </div>
    </div>
</div>