config/routes.rb
Rails.application.routes.draw do

  get 'redeems/index'
  post 'redeems' => "redeems#code_enter"
  get '/deals/redeem_code/:deal_code' => "redeems#redeem_code"
  post '/deals/validate-timings' => "deals#validate_timings"

  delete "/delete_admins/:id" => "admins#destroy"
  resources :specials
  resources :users
  resources :roles

  get "/redeems" => "redeems#index"

  devise_scope :admin do
    authenticated :admin do
      root 'home#dashboard', as: :authenticated_root
    end
    unauthenticated :admin do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "/generate_stamp/:id" => "deals#generate_stamp"

  get "/special_branch_ids/:id" => "specials#get_branch_ids"

  get "/get_prefill_text/:id" => "businesses#get_prefill_text"

  get "/search_keywords" => "businesses#search_keywords"
  post "/add_keyword" => "businesses#add_keyword"
  post "/assign_business" => "admins#assign_business"
  get "/businesses/search_name" => "businesses#search_name"
  get "/admin_businesses/:admin_id" => "admins#get_businesses"

  post "/frequent_search/:type" => "deals#frequent_search"

  get '/get_ruby_date/:date' => "deals#get_ruby_date"

  get '/deals/week_view(/:date(/:window))' => "deals#week_view"

  get '/cloudinary_upload' => "images#cloudinary_upload"

  get '/charts_by_week' => "home#charts_by_week"

  get '/invite_users', to: "admins#invite_users"
  get '/branches/search/', to: "branches#search_by_business_name"
  get '/branches/branches_deals/', to: "branches#branches_deals"
  get '/reinvite/:id', to: "admins#reinvite", as: :reinvite
  resources :admins, only: :new
  post '/send_invitation', to: "admins#send_invitation"

  resources :categories
  resources :businesses do
    collection { post :search, to: 'businesses#index' }
    collection { get :search, to: 'businesses#index' }
    collection { get :autocomplete, to: 'businesses#autocomplete' }
    resources :branches do
      collection { post :search, to: 'branches#index' }
      collection { get :search, to: 'branches#index' }
    end

  end
  resources :countries
  resources :areas
  resources :cities

  resources :deals do
    collection { post :search, to: 'deals#index' }
    collection { get :search, to: 'deals#index' }
  end

  devise_for :admins

end

app/views/admins/_assign_business.html.erb
<div style="display: none;" class="modal fade" id="modal-assign_business" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-top">
    <div class="modal-content">
      <div class="block block-themed block-transparent remove-margin-b">
        <div class="block-header bg-primary-dark">
          <ul class="block-options">
            <li>
              <button data-dismiss="modal" type="button"><i class="si si-close"></i></button>
            </li>
          </ul>
          <h3 class="block-title">Assign Businesses</h3>
        </div>
        <div class="block-content">
                   <h5> Assign to </h5>
          <br/>
          <div class="row">
            <%= form_tag "/assign_business",{remote: true} do %>

              <div class="form-group col-md-12">
                <div class="col-md-12 name">
                  <input class="form-control"  type="text"  name="business_ids" id="business_ids" >
                  <input class="form-control" type="hidden" value="" name="admin_id" id="admin_id" >
                </div>
              </div>
                  <div class="form-group col-md-12">
                    <div class="col-md-12 name">
                      <input type="submit" name="commit" value="Assign" class="btn-lg btn-sm btn-success">
                    </div>
                  </div>
          </div>

        <% end %>

        </div>
      </div>
    </div>
    <div class="modal-content modal-footer">
      <button class="btn btn-sm btn-primary" type="button" data-dismiss="modal"><i class="fa fa-check"></i> Ok</button>
    </div>
  </div>
</div>
</div>

app/views/admins/_table.html.erb
<% @admins.each do |table| %>
  <% invitation_accepted = invitation_accepted?(table) %>
  <tr>
    <td class="text-center"> <%= table.id %> </td>
    <td class="text-center"> <%= table.email %> </td>
    <td class="text-center"> <%= table.role %> </td>
    <td class="text-center"> <%= invitation_accepted ? "Confirmed" : "Not yet Confirmed"  %> </td>
    <td class="text-center"><%= link_to "Assign","#",{data: {id: table.id, target: "#modal-assign_business",toggle: "modal" }, class: "assign_business_link"} %></td>
    <td class="text-center"> 
      <%= link_to "Reinvite", reinvite_path(table.id) if !invitation_accepted %>
    </td>
    <td>
      <%= link_to "Delete", "/delete_admins/#{table.id}", {method: :delete}  %>
    </td>
  </tr>
<% end %>

<%= render "assign_business" %>

app/views/admins/assign_business.js.erb
$("#modal-assign_business").modal("hide");

app/views/admins/invite_users.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
      <div class="col-sm-7">
          <h1 class="page-heading">
              All Users
          </h1>
      </div>
      <div class="col-sm-5 text-right">
        <%= link_to (raw('<i class="fa fa-plus"></i> Invite User')), new_admin_path, {:class => 'btn btn-success'} %>
      </div>
  </div>
</div>
<div class="content">
  <div class="block">
      <div class="block-header">
      </div>
      <div class="block-content">
          <div class="table-responsive">
              <table class="table table-striped table-hover table-header-bg">
                  <thead>
                      <tr>
                          <th class="text-center">Id</th>
                          <th class="text-center">Invited Users</th>
                          <th class="text-center">Role</th>
                          <th class="text-center">Status</th>
                          <th class="text-center">Assign Businesses</th>
                          <th class="text-center">Reinvite</th>
                          <th class="text-center">Delete</th>
                      </tr>
                  </thead>
                  <tbody>
                    <%= render partial: 'table' %>
                  </tbody>
                </table>
          </div>
      </div>
  </div>
</div>
<script>
  actmm("admins")
</script>

app/views/admins/new.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
      <div class="col-sm-7">
      </div>
      <div class="col-sm-5 text-right">
        <%= link_to (raw('<i class="fa fa-plus"></i> All Users')), invite_users_path, {:class => 'btn btn-success'} %>
      </div>
  </div>
</div>
<div class="col-md-6 col-md-offset-3">
	<div class="block block-themed">
		<div class="block-header bg-primary">
		   <h3 class="block-title">Add</h3>
		</div>
		<div class="block-content">
			<%= form_tag send_invitation_path, method: :post, :class => 'form-horizontal push-10-t push-10' do %>
		       <div class="form-group">
		           <div class="col-xs-12">
		               <div class="form-material">
		               	<%= email_field_tag 'email', nil, :class => 'form-control', :placeholder => 'Email' %>
		                   <label>Enter Email</label>
		               </div>
		           </div>
		       </div>
		       <div class="form-group">
		           <div class="col-xs-12">
		               <div class="form-material">
		               	<%= select_tag 'role', options_for_select(Role.all.map {|r| r.name.titleize}), :class => 'form-control' %>
		                   <label>Select role</label>
		               </div>
		           </div>
		       </div>
		       <div class="form-group">
		           <div class="col-xs-12">
		           	<%= submit_tag 'Invite', :class => 'btn btn-sm btn-primary' %>
		           </div>
		       </div>
		   <% end %>
		</div>
	</div>
</div>