config/routes.rb
Rails.application.routes.draw do

  get 'redeems/index'
  post 'redeems' => "redeems#code_enter"
  get '/deals/redeem_code/:deal_code' => "redeems#redeem_code"
  post '/deals/validate-timings' => "deals#validate_timings"

  delete "/delete_admins/:id" => "admins#destroy"
  resources :specials
  resources :users
  resources :roles

  get "/redeems" => "redeems#index"

  devise_scope :admin do
    authenticated :admin do
      root 'home#dashboard', as: :authenticated_root
    end
    unauthenticated :admin do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "/generate_stamp/:id" => "deals#generate_stamp"

  get "/special_branch_ids/:id" => "specials#get_branch_ids"

  get "/get_prefill_text/:id" => "businesses#get_prefill_text"

  get "/search_keywords" => "businesses#search_keywords"
  post "/add_keyword" => "businesses#add_keyword"
  post "/assign_business" => "admins#assign_business"
  get "/businesses/search_name" => "businesses#search_name"
  get "/admin_businesses/:admin_id" => "admins#get_businesses"

  post "/frequent_search/:type" => "deals#frequent_search"

  get '/get_ruby_date/:date' => "deals#get_ruby_date"

  get '/deals/week_view(/:date(/:window))' => "deals#week_view"

  get '/cloudinary_upload' => "images#cloudinary_upload"

  get '/charts_by_week' => "home#charts_by_week"

  get '/invite_users', to: "admins#invite_users"
  get '/branches/search/', to: "branches#search_by_business_name"
  get '/branches/branches_deals/', to: "branches#branches_deals"
  get '/reinvite/:id', to: "admins#reinvite", as: :reinvite
  resources :admins, only: :new
  post '/send_invitation', to: "admins#send_invitation"

  resources :categories
  resources :businesses do
    collection { post :search, to: 'businesses#index' }
    collection { get :search, to: 'businesses#index' }
    collection { get :autocomplete, to: 'businesses#autocomplete' }
    resources :branches do
      collection { post :search, to: 'branches#index' }
      collection { get :search, to: 'branches#index' }
    end

  end
  resources :countries
  resources :areas
  resources :cities

  resources :deals do
    collection { post :search, to: 'deals#index' }
    collection { get :search, to: 'deals#index' }
  end

  devise_for :admins

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :permissions
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def set_permissions
    @permission_actions = %w(create update delete list).sort
    @permissions = Permission.all.group_by &:subject_class
  end

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
    set_permissions
  end

  # GET /roles/1/edit
  def edit
    set_permissions
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to roles_path, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to roles_path, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit!
    end
end

app/views/roles/_form.html.erb
<%= form_for(@role,:html => {class: "form-horizontal"}) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% @role.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-12">
    <div class="block block-themed">
      <div class="block-header bg-primary">
        <h3 class="block-title">Basic</h3>
      </div>

      <div class="block-content">

        <%= form_element("name",f,:text_field,[class: "form-control"],4) %>

        <%= form_element("description",f,:text_area,[size: "200x5", class: "form-control"],8) %>

        <div class="form-group"></div>

      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="block block-themed">
      <div class="block-header bg-primary">
        <h3 class="block-title">Permissions</h3>
      </div>

      <div class="block-content">

        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th class="text-center">Resource</th>
              <% @permission_actions.each do |action| %>
                <th class="text-center"><%= action %></th>
              <% end %>
            </tr>
          </thead>
          <tbody>
              <% @permissions.keys.sort.each do |cl| %>
                <tr class="text-center">
                  <td><%= cl %></td>
                  <% (@permissions[cl].sort_by {|i| i.action}).each do |record| %>
                    <td><%= check_box_tag "role[permission_ids][]",record.id, @role.permissions.include?(record) %></td>
                  <% end %>
                </tr>
              <% end %>
          </tbody>
        </table>
        <div class="form-group"></div>
      </div>
    </div>
  </div>

  <div class="row form-group text-center">
    <div class="col-xs-12">
      <div class="form-material">
        <p><%= f.submit "Save Role", :class => "btn-lg btn-sm btn-success"%></p>
      </div>
    </div>
  </div>

<% end %>

app/views/roles/_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th class="text-center">Id</th>
      <th class="text-center">Name</th>
      <th class="text-center">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @roles.each do |role| %>
      <tr class="text-center">
        <td class="text-center"> <%= role.id %> </td>
        <td class="text-center"> <%= link_to role.name, edit_role_path(role) %> </td>
        <td class="text-center">
            <%= link_to (raw('<i class="fa fa-trash-o fa-2"></i>')), role, method: :delete, class: 'btn-sm btn-danger', data: { confirm: 'Are you sure?'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/roles/edit.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        Edit Role
      </h1>
    </div>
  </div>
</div>


<%= render 'form' %>

<script>
actmm("roles");
</script>

app/views/roles/index.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        Roles <small>(<%= @roles.count %>)</small>
      </h1>
    </div>
    <div class="col-sm-5 text-right">
      <%= link_to (raw('<i class="fa fa-plus"></i> New Role')), new_role_path, {:class => 'btn btn-success'} %>
    </div>
  </div>
</div>

<div class="block">
  <div class="block-content">
    <% if @roles.present? %>
      <%= render 'table' %>
    <% else %>
      <h3 class="text-center" style="padding-bottom:20px;">Currently no roles to show.</h3>
    <% end %>
  </div>
</div>
<script>
  actmm("roles");
</script>

app/views/roles/new.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-7">
      <h1 class="page-heading">
        New Role
      </h1>
    </div>
  </div>
</div>


<%= render 'form' %>

<script>
actmm("roles");
</script>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>